enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://www.npmjs.com/":
    npmAlwaysAuth: true

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  globalsign:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://registry.yarnpkg.com/"

yarnPath: .yarn/releases/yarn-4.10.2.cjs
